[package]
name = "oxide-auth"
version = "0.5.0"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]
repository = "https://github.com/HeroicKatora/oxide-auth.git"
edition = "2018"

description = "A OAuth2 library for common web servers, featuring a set of configurable and pluggable backends."
readme = "Readme.md"

keywords = ["oauth", "server", "oauth2"]
categories = ["web-programming::http-server", "authentication"]
license = "MIT OR Apache-2.0"

autoexamples = false

[dependencies]
base64 = "0.12"
chrono = "0.4.2"
hmac = "0.9.0"
once_cell = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.9.1"
subtle = "2.2.2"
rand = "0.7.3"
rust-argon2 = "0.8.2"
rmp-serde = "0.14"
url = "2"
log = "0.4"

[dev-dependencies]
reqwest = "0.10.8"

[package.metadata.docs.rs]
features = []
