[package]
name = "db-example"
version = "0.1.0"
authors = ["liujing <liujingb@mail.taiji.com.cn>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oxide-auth = { version = "0.5.0-preview.0", path = "../../../oxide-auth" }
oxide-auth-actix = { version = "0.1.0", path = "./../../../oxide-auth-actix" }
oxide-auth-db = { version = "0.1.0", path = "./../../", features = ["redis-isolate-scylla-cluster"]}
actix = "0.10"
actix-rt = "1"
actix-web = "3"
env_logger = "0.7"
futures = "0.3"
reqwest = "=0.9.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1"
url = "2"
anyhow = "1.0"
log = "0.4"
tokio = { version = "1", features = ["macros", "io-util"] }
